services:
  eden.validator_1:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - $HOME/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=3
    command: 
      - poetry
      - run
      - python
      - -m 
      - eden_subnet.validator.cli
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
